#!/bin/bash
cd /var/www/supdashboard/scripts
# setting variables
user="root"
password="password"
database="supdashboarddb"

# creating database
echo "creating database..."
mysql -u `echo $user` -p`echo $password` < create_database
echo "Done."

# migrating and seeding database
cd /var/www/supdashboard
php artisan migrate
php artisan db:seed