#!/bin/bash
# setting variables
user="root"
password="password"
database="supdashboarddb"

# creating database
echo "creating database..."
mysql -u `echo $user` -p`echo $password` < create_database
echo "Done."

# migrating and seeding database
cd ..
php artisan migrate
php artisan db:seed
 